name: tracev2
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio       
  - rioxarray
  - numpy
  - geopandas     
  - matplotlib
  - seaborn     
  - pandas
  - netcdf4
  - earthengine-api
  - geemap
  - spectral
